name: publish-docs 

on:
  push:
    # Publish `main` as latest, and when pushes are done to branches with "v-doc" prefix
    branches:
      - main
      - docs-v*

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0 # fetch all commits/branches
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: 3.x
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install Python dependencies
        run: pip install -r ./mkdocs-requirements.txt
      - name: Configure git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy docs
        run: |
          # Strip git ref prefix from version
          echo "${{ github.ref }}"
          # Extract the version and if it is in `docs-v` form, strip that off the version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' -e 's/^docs-v//')
          # Run a script to prepare all the files that have to be moved/updated to publish cleanly
          ./scripts/prepmkdocs.sh
          # Populate overrides for the current version, and then remove to not apply if VERSION is main branch
          OVERRIDE=overrides/main.html
          echo -e "{% extends \"base.html\" %}\n\n{% block outdated %}\n  You are viewing the documentation for ACA-Py Release $VERSION.\n{% endblock %}" >$OVERRIDE
          # If building from main, use latest as ALIAS and remove the override
          [ "$VERSION" == "main" ] && ALIAS=latest && rm $OVERRIDE
          echo $VERSION $ALIAS
          mike deploy --push --update-aliases $VERSION $ALIAS
          mike set-default latest
